/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WatchVideoIdImport } from './routes/watch/$videoId'
import { Route as SearchQueryImport } from './routes/search/$query'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WatchVideoIdRoute = WatchVideoIdImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRoute,
} as any)

const SearchQueryRoute = SearchQueryImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/search/$query': {
      id: '/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof SearchQueryImport
      parentRoute: typeof rootRoute
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search/$query': typeof SearchQueryRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search/$query': typeof SearchQueryRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/search/$query': typeof SearchQueryRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search/$query' | '/watch/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search/$query' | '/watch/$videoId'
  id: '__root__' | '/' | '/search/$query' | '/watch/$videoId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchQueryRoute: typeof SearchQueryRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchQueryRoute: SearchQueryRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/search/$query",
        "/watch/$videoId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/search/$query": {
      "filePath": "search/$query.tsx"
    },
    "/watch/$videoId": {
      "filePath": "watch/$videoId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
